baseurl = "https://ryanfakir.github.io/" 
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Peng Yan"
title = "Peng Yan"
pygmentsuseclasses = true
# disqusshortname = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false


[permalinks]
fixed = ":title/"
blog = ":slug/"

[params]
author = "Peng Yan"
# gravatar = "" # do not use in the same time as Avatar
# avatar = "" # path to image in static dir e.g img/avatar.png (do not use in the same time as Gravatar)
# cachebuster = false # FIXME: See issue #32.
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "I am nobody, but with curiosity"
email = "pengyan@buffalo.edu"
faviconfile = "img/leaf.ico"
gatracker = "XYZ"
github = "//github.com/ryanfakir"
highlightjs = true
highlightjslanguages = ["go"] # additional languages not included in the "common" set
initials = "ad" # Displayed on single post page; DEPRECATED in v0.3.0.
lang = "en"
linkedin = "//linkedin.com/in/ryanfakir"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

# extracssfiles = [ "/css/override.css" ] # In your `static/css`, add/remove files as necessary.